name: Push to AWS Public ECR
on: [push]
jobs:
  ecr-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Public ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws

      - name: Build, tag, and push image to Amazon Public ECR
        env:
          ECR_REGISTRY: public.ecr.aws
          ECR_REPOSITORY: andreswebs/promtail
          ORIGIN_REPOSITORY: grafana/promtail
          IMAGE_TAG: "2.3.0"
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" --build-arg "IMAGE=$ORIGIN_REPOSITORY:$IMAGE_TAG" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
